### ISSUE TITLE
Lay z Spa San Fransisco shown offline

### ISSUE THREAD

**Issue by SoerenRa** [cdpuk/ha-bestway#26] opened 2023-06-20 18:52 UTC
Hey, i currently installed this Integration into my ha instance for the Lay-Z-Spa Hydrojet Pro San Fransisco. The login worked but now it shows my device as offline but in the Bestway app it’s shown online and I can edit the settings as usual. Is there any workaround? 

For Logs see next Post

**Comment by SoerenRa** [comment] 2023-06-20 19:17
Lay Z Spa San Fransisco Hydro Jet Pro. 

Here are the Logs: 

Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: custom_components.bestway.bestway
Source: custom_components/bestway/bestway.py:252 
Integration: Bestway (documentation, issues) 
First occurred: 20:59:58 (34 occurrences) 
Last logged: 21:16:24

Unexpected missing key ''system_err1'' while decoding device attributes {"E19": 0, "E18": 0, "E32": 0, "E31": 0, "E30": 0, "E11": 0, "E10": 0, "E13": 0, "E12": 0, "E15": 0, "E14": 0, "E17": 0, "E16": 0, "word5": 130, "word4": 0, "word7": 34, "word6": 0, "word1": 0, "word0": 0, "E29": 0, "word2": 130, "option6": 10244, "ver": 12614, "E22": 0, "jet": 0, "E23": 0, "power": 1, "Tnow": 34, "option7": 10260, "option4": 60, "option5": 27176, "option2": 0, "option3": 30, "option0": 59940, "option1": 59940, "E24": 0, "E25": 0, "E26": 0, "E27": 0, "E20": 0, "E21": 0, "E08": 0, "E09": 0, "E06": 0, "E07": 0, "E04": 0, "E05": 0, "E02": 0, "E03": 0, "E01": 0, "bit7": 1, "heat": 3, "Tunit": 1, "wave": 0, "word3": 0, "Tset": 35, "filter": 2, "E28": 0, "bit6": 1, "bit5": 1, "bit4": 0, "bit3": 1, "bit2": 0}
Unexpected missing key ''system_err1'' while decoding device attributes {"E19": 0, "E18": 0, "E32": 0, "E31": 0, "E30": 0, "E11": 0, "E10": 0, "E13": 0, "E12": 0, "E15": 0, "E14": 0, "E17": 0, "E16": 0, "word5": 131, "word4": 0, "word7": 34, "word6": 0, "word1": 0, "word0": 0, "E29": 0, "word2": 131, "option6": 10244, "ver": 12614, "E22": 0, "jet": 0, "E23": 0, "power": 1, "Tnow": 34, "option7": 10260, "option4": 60, "option5": 27176, "option2": 0, "option3": 30, "option0": 59940, "option1": 59940, "E24": 0, "E25": 0, "E26": 0, "E27": 0, "E20": 0, "E21": 0, "E08": 0, "E09": 0, "E06": 0, "E07": 0, "E04": 0, "E05": 0, "E02": 0, "E03": 0, "E01": 0, "bit7": 1, "heat": 3, "Tunit": 1, "wave": 0, "word3": 0, "Tset": 35, "filter": 2, "E28": 0, "bit6": 1, "bit5": 1, "bit4": 0, "bit3": 1, "bit2": 0}
Unexpected missing key ''system_err1'' while decoding device attributes {"E19": 0, "E18": 0, "E32": 0, "E31": 0, "E30": 0, "E11": 0, "E10": 0, "E13": 0, "E12": 0, "E15": 0, "E14": 0, "E17": 0, "E16": 0, "word5": 131, "word4": 0, "word7": 35, "word6": 0, "word1": 0, "word0": 0, "E29": 0, "word2": 131, "option6": 10244, "ver": 12614, "E22": 0, "jet": 0, "E23": 0, "power": 1, "Tnow": 34, "option7": 10260, "option4": 60, "option5": 27176, "option2": 0, "option3": 30, "option0": 59940, "option1": 59940, "E24": 0, "E25": 0, "E26": 0, "E27": 0, "E20": 0, "E21": 0, "E08": 0, "E09": 0, "E06": 0, "E07": 0, "E04": 0, "E05": 0, "E02": 0, "E03": 0, "E01": 0, "bit7": 1, "heat": 3, "Tunit": 1, "wave": 0, "word3": 0, "Tset": 35, "filter": 2, "E28": 0, "bit6": 1, "bit5": 1, "bit4": 0, "bit3": 1, "bit2": 0}
Unexpected missing key ''system_err1'' while decoding device attributes {"E19": 0, "E18": 0, "E32": 0, "E31": 0, "E30": 0, "E11": 0, "E10": 0, "E13": 0, "E12": 0, "E15": 0, "E14": 0, "E17": 0, "E16": 0, "word5": 132, "word4": 0, "word7": 35, "word6": 0, "word1": 0, "word0": 0, "E29": 0, "word2": 132, "option6": 10244, "ver": 12614, "E22": 0, "jet": 0, "E23": 0, "power": 1, "Tnow": 34, "option7": 10260, "option4": 60, "option5": 27176, "option2": 0, "option3": 30, "option0": 59940, "option1": 59940, "E24": 0, "E25": 0, "E26": 0, "E27": 0, "E20": 0, "E21": 0, "E08": 0, "E09": 0, "E06": 0, "E07": 0, "E04": 0, "E05": 0, "E02": 0, "E03": 0, "E01": 0, "bit7": 1, "heat": 3, "Tunit": 1, "wave": 0, "word3": 0, "Tset": 35, "filter": 2, "E28": 0, "bit6": 1, "bit5": 1, "bit4": 0, "bit3": 1, "bit2": 0}
Unexpected missing key ''system_err1'' while decoding device attributes {"E19": 0, "E18": 0, "E32": 0, "E31": 0, "E30": 0, "E11": 0, "E10": 0, "E13": 0, "E12": 0, "E15": 0, "E14": 0, "E17": 0, "E16": 0, "word5": 133, "word4": 0, "word7": 35, "word6": 0, "word1": 0, "word0": 0, "E29": 0, "word2": 133, "option6": 10244, "ver": 12614, "E22": 0, "jet": 0, "E23": 0, "power": 1, "Tnow": 34, "option7": 10260, "option4": 60, "option5": 27176, "option2": 0, "option3": 30, "option0": 59940, "option1": 59940, "E24": 0, "E25": 0, "E26": 0, "E27": 0, "E20": 0, "E21": 0, "E08": 0, "E09": 0, "E06": 0, "E07": 0, "E04": 0, "E05": 0, "E02": 0, "E03": 0, "E01": 0, "bit7": 1, "heat": 3, "Tunit": 1, "wave": 0, "word3": 0, "Tset": 35, "filter": 2, "E28": 0, "bit6": 1, "bit5": 1, "bit4": 0, "bit3": 1, "bit2": 0}

**Comment by cdpuk** [comment] 2023-06-20 20:01
This is a duplicate of #16. HydroJet Pro devices are not currently supported, however some work is underway on https://github.com/cdpuk/ha-bestway/tree/generic-bestway attempting to resolve this. Initially this will support Bestway pool filters as per #23, with Hydrojet Pro coming after, due to it being more complex.

**Closed by cdpuk** 2023-06-20 20:01 UTC
