### ISSUE TITLE
Spa Errors entity reports problems when there are none

### ISSUE THREAD

**Issue by pdecat** [cdpuk/ha-bestway#76] opened 2024-09-17 12:05 UTC
## Version of the custom_component

1.6.0

## Bestway device

[Bestway Lay-Z-Spa Hydrojet Pro with wifi EU P07033](https://fr.bestway.eu/p/pompe-de-filtration-bestway-pour-layzspa-hydrojet-avec-wifi-eu)

## Describe the bug

The Spa Errors entity reports problem when there are none:

![image](https://github.com/user-attachments/assets/562cee42-4372-44c5-acc4-73fd2fbda607)
![image](https://github.com/user-attachments/assets/8bbc6a56-f617-4ae7-b700-d0a0520f327d)

It may be caused by interruption of heating when max temp is reached:

![image](https://github.com/user-attachments/assets/59936460-609f-4d28-a20f-d292e1dc79e7)

If I check the Bestway app and the spa pump display directly, I see no error.

## Logs

Nothing at the time of the last problem as I did not enable debug logging yet:
```text
2024-09-17 07:34:32.493 ERROR (MainThread) [custom_components.bestway.coordinator] Data update failed
  File "/config/custom_components/bestway/coordinator.py", line 37, in _async_update_data
  File "/config/custom_components/bestway/bestway/api.py", line 168, in fetch_data
  File "/config/custom_components/bestway/bestway/api.py", line 435, in _do_get
  File "/config/custom_components/bestway/coordinator.py", line 35, in _async_update_data
2024-09-17 07:34:32.495 ERROR (MainThread) [custom_components.bestway.coordinator] Error fetching Bestway API data: Error communicating with API:
2024-09-17 07:35:02.631 INFO (MainThread) [custom_components.bestway.coordinator] Fetching Bestway API data recovered
2024-09-17 13:48:37.614 DEBUG (MainThread) [custom_components.bestway.bestway.api] Device list refreshed: {"devices": [{"protoc": 3, "ws_port": 8080, "port_s": 8883, "gw_did": null, "host": "eum2m.gizwits.com", "sleep_duration": 3600, "port": 1883, "mcu_soft_version": "D3071011", "product_key": "********************************", "state_last_timestamp": 1726573716, "role": "owner", "is_sandbox": false, "type": "normal", "product_name": "Hydrojet_Pro", "is_disabled": false, "mcu_hard_version": "P3A30005", "wifi_soft_version": "04X3000B", "dev_alias": "Spa", "mesh_id": null, "is_online": true, "dev_label": [], "wss_port": 8880, "remark": "23", "did": "**********************", "mac": "************", "passcode": "**********", "wifi_hard_version": "0ESP32C3", "is_low_power": false}]}
2024-09-17 13:48:37.663 DEBUG (MainThread) [custom_components.bestway.bestway.api] New data received for device **********************
2024-09-17 13:48:37.663 DEBUG (MainThread) [custom_components.bestway.bestway.api] Status for device type 'Hydrojet_Pro' returned: {"E19": 0, "E18": 0, "E32": 1, "E31": 0, "E30": 0, "E11": 0, "E10": 0, "E13": 0, "E12": 0, "E15": 0, "E14": 0, "E17": 0, "E16": 0, "word5": 184, "word4": 0, "word7": 100, "word6": 0, "word1": 0, "word0": 0, "E29": 0, "word2": 184, "option6": 10244, "ver": 931, "E22": 0, "jet": 0, "E23": 0, "power": 1, "Tnow": 41, "option7": 10260, "option4": 60, "option5": 27176, "option2": 0, "option3": 30, "option0": 59940, "option1": 59940, "E24": 0, "E25": 0, "E26": 0, "E27": 0, "E20": 0, "E21": 0, "E08": 0, "E09": 0, "E06": 0, "E07": 0, "E04": 0, "E05": 0, "E02": 0, "E03": 0, "E01": 0, "bit7": 0, "heat": 4, "Tunit": 1, "wave": 0, "word3": 0, "Tset": 40, "filter": 2, "E28": 0, "bit6": 0, "bit5": 0, "bit4": 0, "bit3": 0, "bit2": 1}

```

**Comment by alexkrishnan** [comment] 2024-09-17 15:05
Related to/duplicate of https://github.com/cdpuk/ha-bestway/issues/66

**Comment by alexkrishnan** [comment] 2024-09-17 15:49
To see the cause of the error, click the Attributes section in the Spa Error screen. Your logs indicate E32 which is currently an unknown error.

**Comment by pdecat** [comment] 2024-09-17 21:32
Indeed, thanks!

**Closed** 2024-09-17 21:47 UTC
