### ISSUE TITLE
Login information is not valid?

### ISSUE THREAD

**Issue by LasseTheDude** [cdpuk/ha-bestway#1] opened 2022-06-03 20:29 UTC
Every time I try to login I got a errror message for the user account!

**Comment by cdpuk** [comment] 2022-06-06 07:07
Can you confirm that you've got the Bestway app installed and working on your phone? (not the lay-z-spa app)

Also can you let us know the exact error message and any additional relevant information from the HA log?

**Comment by LasseTheDude** [comment] 2022-06-08 11:51
Yes I can confirm that I use the bestway app and it works perfect on my iPhone.

"User account does not exist" is the error message.

I live in Norway if thats important.

**Comment by bananfluen** [comment] 2022-06-08 18:45
Exaxt same problem here. I also live in Norway.

**Comment by sdneusta** [comment] 2022-06-13 07:09
I was close to report same problems too.
But after using right "bestway" app instead of "lay-z-spa" app. Ge through registration.
Because I suffered a lot, "User account does not exist" errors against bestway.

After I managed it, I couldn't be more pleased how fine it works with Siri.
Made the bestway app in my case totally obsolete in daily use.

**Comment by sdneusta** [comment] 2022-06-13 08:25
I've been using an iPhone app. Mine was just called "bestway"-App. 
But there are plenty of other bestway apps, even on iphone.
This one is what I use: https://apps.apple.com/de/app/bestway-smart-hub/id1456731336

**Comment by sdneusta** [comment] 2022-06-13 08:38
> . Same App it seems... May i ask what is your location? as its seems related to geo
> 
> > I've been using an iPhone app. Mine was just called "bestway"-App. But there are plenty of other bestway apps, even on iphone. This one is what I use: https://apps.apple.com/de/app/bestway-smart-hub/id1456731336

Sure, Germany.

The App requested each time location information. 
Maybe it's because of different Wi-Fi restrictions between several countries.
Did you create and activate your registration complete on bestway app? 
Could you control your Spa via this app?
I think this is mandatory.

But I'm not a dev on this project. 
I'm just a happy consumer.

**Comment by tet024** [comment] 2022-06-13 08:47
Hello, 
I reside in Malta ... Yes i'm using the Best  Way app to control the spa and it works fine.

Issue is that i wasn't able to find any related logs to why its failing. 




> > . Same App it seems... May i ask what is your location? as its seems related to geo
> > > I've been using an iPhone app. Mine was just called "bestway"-App. But there are plenty of other bestway apps, even on iphone. This one is what I use: https://apps.apple.com/de/app/bestway-smart-hub/id1456731336
> 
> Sure, Germany.
> 
> The App requested each time location information. Maybe it's because of different Wi-Fi restrictions between several countries. Did you create and activate your registration complete on bestway app? Could you control your Spa via this app? I think this is mandatory.
> 
> But I'm not a dev on this project. I'm just a happy consumer.

**Comment by LasseTheDude** [comment] 2022-06-13 16:44
Norway here. Bestway app. I hope @cdpuk can look into this fast. I really want my bath into HA 😇

**Comment by LasseTheDude** [comment] 2022-06-13 16:58
I found the solution! Delete your bath from the old account. Make a new one with Germany as the country with the same email and a different password. Now it works like a charm! 😃

**Comment by cdpuk** [comment] 2022-06-13 18:44
I've been keeping a watch on this thread - glad to see there seems to be a way to get it working 😄 

I had a bit of a play with the login request that HA has to make - there's a `lang` parameter that was hard coded to `en`. I tried passing other country codes but it always succeeded for my account. The only other data we pass across is the username and password.

Sounds like perhaps only certain countries will work when you create the Bestway app account. Mine will have been UK, and sounds like Germany works too.

Has anybody else had success following @LasseTheDude's workaround? If so, I'll update the README and close the issue.

**Comment by DavidVankan** [comment] 2022-06-13 19:52
I can confirm that it is working after creating new account with country German

**Comment by cdpuk** [comment] 2022-06-13 20:32
Great. I'll update the README.

**Closed by cdpuk** 2022-06-13 20:32 UTC

**Comment by bananfluen** [comment] 2022-06-13 20:54
Worked here also changing to Germany. Great, thanks! :-)

**Comment by Schaussi** [comment] 2023-05-15 19:13
In my case it did _not_ work with
- "Lay-Z-Spa" app. Connecting within the app worked after about 10 retries.
- HA integration login: _account does not exist_ (and EU gateway did not work at all)

It **worked** with

- "_Bestway Smart Home_" app (Android). After install, it appears in the menu with a "B" icon and text "Multiple Image Select" :)
- Account created in app: Europe/Austria, the pump connected flawlessly
- HA integration login: Only **US** gateway worked (not EU)
